export const operators: Record<string, string> = {
  '=': '=',
  eq: '=',
  '!=': '!=',
  neq: '!=',
  '>': '>',
  gt: '>',
  '<': '<',
  lt: '<',
  '>=': '>=',
  gte: '>=',
  '<=': '<=',
  lte: '<=',
  like: 'LIKE',
  ilike: 'ILIKE',
  nlike: 'NOT LIKE',
  nilike: 'NOT ILIKE',
  is: 'IS',
  isnot: 'IS NOT',
  in: 'IN',
  nin: 'NOT IN',
  bw: 'BETWEEN',
  nbw: 'NOT BETWEEN',
  fts: '@@',
};
