export enum ControlType {
  Text = 'text',
  Textarea = 'textarea',
  Number = 'number',
  Phone = 'phone',
  Email = 'email',
  Password = 'password',
  Picker = 'picker',
  OneChoose = 'onechoose',
  MultiChoose = 'multichoose',
  Date = 'date',
  Time = 'time',
  Times = 'times',
  DateTime = 'datetime',
  File = 'file',
  Files = 'files',
  Image = 'image',
  Images = 'images',
  Video = 'video',
  Videos = 'videos',
  Audio = 'audio',
  Audios = 'audios',
  Document = 'document',
  Documents = 'documents',
  Link = 'link',
}
